---
sourceClouds:
- /home/gchahine/outbound/0/semantic_icp_3.pcd
- /home/gchahine/outbound/1/semantic_icp_3.pcd
sourceTrajectories:
- /home/gchahine/outbound/0/semantic_icp_3.csv
- /home/gchahine/outbound/1/semantic_icp_3.csv
mapRegistration: "gps"
semantics: "True"
voxelSize: "0.2"
pathOut: "/home/gchahine/matcherOutput/"
icpConfig: "/home/gchahine/packages/dream-multi-matcher/icpConfig/icp_param.yaml"
icpConfigLoopClosure: "/home/gchahine/packages/dream-multi-matcher/icpConfig/icp_param_lc.yaml"
icpInputFilters: "/home/gchahine/packages/dream-multi-matcher/icpConfig/input_filters.yaml"
icpPostFilters: "/home/gchahine/packages/dream-multi-matcher/icpConfig/mapPost_filters.yaml"
icpComputeProbDynamic: "True"
autoMatch: "true"
autoLoopClose: "true"
loopCloseKF: "semantic_icp_lc"
autoMatchDir:
- "/mnt/storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/0/"
- "/mnt/storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/1/"
- "/mnt/storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/2/"
- "/mnt/storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/3/"
- "/mnt/storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/4/"
- "/mnt/storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/5/"
- "/mnt/storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/6/"
- "/mnt/storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/keyframes/new/7/"
autoNameTemplate: "semantic_icp_"
autoKeyFrameDelta: "25"  
autoVerify: "True"


