---
sourceClouds:
- /home/gchahine/cloud_accumulator/0/gps_global_1.pcd
- /home/gchahine/cloud_accumulator/0/gps_global_2.pcd
sourceTrajectories:
- SKIP
- SKIP
mapRegistration: "gps"
semantics: "False"
voxelSize: "0.01"
pathOut: "/home/gchahine/aligned_calib"
icpConfig: "/home/gchahine/packages/dream-multi-matcher/icpConfig/icp_param.yaml"
icpConfigLoopClosure: "/home/gchahine/packages/dream-multi-matcher/icpConfig/icp_param_lc.yaml"
icpInputFilters: "/home/gchahine/packages/dream-multi-matcher/icpConfig/input_filters.yaml"
icpPostFilters: "/home/gchahine/packages/dream-multi-matcher/icpConfig/mapPost_filters.yaml"
icpComputeProbDynamic: "True"
autoMatch: "false"
autoLoopClose: "true"
loopCloseKF: "semantic_icp_lc"
autoMatchDir:
- "/home/gpu_user/gchahine/mapperOutput_full/0/"
- "/home/gpu_user/gchahine/mapperOutput_full/1/"
- "/home/gpu_user/gchahine/mapperOutput_full/2/"
- "/home/gpu_user/gchahine/mapperOutput_full/3/"
- "/home/gpu_user/gchahine/mapperOutput_full/4/"
- "/home/gpu_user/gchahine/mapperOutput_full/5/"
- "/home/gpu_user/gchahine/mapperOutput_full/6/"
- "/home/gpu_user/gchahine/mapperOutput_full/7/"
- "/home/gpu_user/gchahine/mapperOutput_full/8/"
- "/home/gpu_user/gchahine/mapperOutput_full/9/"
- "/home/gpu_user/gchahine/mapperOutput_full/10/"
- "/home/gpu_user/gchahine/mapperOutput_full/11/"
autoNameTemplate: "semantic_icp_"
autoKeyFrameDelta: "25"  
autoVerify: "True"
