---
sourceClouds:
- /home/gpu_user/gchahine/mapperOutput_Husky/0/icp_local_semantics.pcd
- /home/gpu_user/gchahine/mapperOutput_Husky/1/icp_local_semantics.pcd
- /home/gpu_user/gchahine/mapperOutput_Husky/2/icp_local_semantics.pcd
- /home/gpu_user/gchahine/mapperOutput_Husky/3/icp_local_semantics.pcd
- /home/gpu_user/gchahine/mapperOutput_Husky/4/icp_local_semantics.pcd
- /home/gpu_user/gchahine/mapperOutput_Husky/5/icp_local_semantics.pcd
- /home/gpu_user/gchahine/mapperOutput_Husky/6/icp_local_semantics.pcd
- /home/gpu_user/gchahine/mapperOutput_Husky/7/icp_local_semantics.pcd
- /home/gpu_user/gchahine/mapperOutput_Husky/8/icp_local_semantics.pcd
- /home/gpu_user/gchahine/mapperOutput_Husky/9/icp_local_semantics.pcd
- /home/gpu_user/gchahine/mapperOutput_Husky/10/icp_local_semantics.pcd
- /home/gpu_user/gchahine/mapperOutput_Husky/11/icp_local_semantics.pcd
- /home/gpu_user/gchahine/mapperOutput_Husky/12/icp_local_semantics.pcd
sourceTrajectories:
- /home/gpu_user/gchahine/mapperOutput_Husky/0/icp_local_semantics.csv
- /home/gpu_user/gchahine/mapperOutput_Husky/1/icp_local_semantics.csv
- /home/gpu_user/gchahine/mapperOutput_Husky/2/icp_local_semantics.csv
- /home/gpu_user/gchahine/mapperOutput_Husky/3/icp_local_semantics.csv
- /home/gpu_user/gchahine/mapperOutput_Husky/4/icp_local_semantics.csv
- /home/gpu_user/gchahine/mapperOutput_Husky/5/icp_local_semantics.csv
- /home/gpu_user/gchahine/mapperOutput_Husky/6/icp_local_semantics.csv
- /home/gpu_user/gchahine/mapperOutput_Husky/7/icp_local_semantics.csv
- /home/gpu_user/gchahine/mapperOutput_Husky/8/icp_local_semantics.csv
- /home/gpu_user/gchahine/mapperOutput_Husky/9/icp_local_semantics.csv
- /home/gpu_user/gchahine/mapperOutput_Husky/10/icp_local_semantics.csv
- /home/gpu_user/gchahine/mapperOutput_Husky/11/icp_local_semantics.csv
- /home/gpu_user/gchahine/mapperOutput_Husky/12/icp_local_semantics.csv
mapRegistration: "gps"
semantics: "True"
voxelSize: "0.15"
pathOut: "/home/gpu_user/gchahine/matcherOutput/15/"
icpConfig: "/home/gpu_user/gchahine/packages/dream-multi-matcher/icpConfig/icp_param.yaml"
icpConfigLoopClosure: "/home/gpu_user/gchahine/packages/dream-multi-matcher/icpConfig/icp_param_lc.yaml"
icpInputFilters: "/home/gpu_user/gchahine/packages/dream-multi-matcher/icpConfig/input_filters.yaml"
icpPostFilters: "/home/gpu_user/gchahine/packages/dream-multi-matcher/icpConfig/mapPost_filters.yaml"
icpComputeProbDynamic: "True"
autoMatch: "true"
autoLoopClose: "true"
loopCloseKF: "semantic_icp_lc"
autoMatchDir:
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/0/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/1/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/2/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/3/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/4/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/5/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/6/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/7/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/8/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/9/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/10/"
- "/mnt/dream-storage/Backpack_Dataset/cross-seasonal-semantic-dataset/lake-bPearl/post/mapper-12-months-2/11/"
autoNameTemplate: "semantic_icp_"
autoKeyFrameDelta: "25"  
autoVerify: "True"
